from __future__ import annotations
from typing import Protocol, Optional
from .entities import Task, Session

class TaskRepository(Protocol):
    def list_tasks(self, *, status: str | None = None) -> list[Task]: ...
    def get(self, task_id: str) -> Optional[Task]: ...
    def upsert(self, task: Task) -> None: ...
    def next_id(self) -> str: ...

class SessionRepository(Protocol):
    def list_sessions(self) -> list[Session]: ...
    def get(self, session_id: str) -> Optional[Session]: ...
    def upsert(self, session: Session) -> None: ...
    def next_id(self) -> str: ...
