from __future__ import annotations
from typing import Protocol, Optional
from .entities import Task

class TaskRepository(Protocol):
    def list_tasks(self, *, status: str | None = None) -> list[Task]: ...
    def get(self, task_id: str) -> Optional[Task]: ...
    def upsert(self, task: Task) -> None: ...
    def next_id(self) -> str: ...
